package deployer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/kingyoung/bbsit/internal/types"
	"gopkg.in/yaml.v3"
)

// stackConfig is the YAML format for stack config mode.
// It mirrors the form fields so both modes generate compose.yaml the same way.
type stackConfig struct {
	RegistryImage string            `yaml:"registry_image"`
	ImageTag      string            `yaml:"image_tag"`
	Ports         []types.PortMapping `yaml:"ports"`
	Volumes       []types.VolumeMount `yaml:"volumes"`
	EnvVars       map[string]string `yaml:"env_vars"`
	ExtraOptions  string            `yaml:"extra_options"`
}

// WriteComposeFiles writes compose.yaml, compose.override.yaml, and .env to the stack directory.
// It also ensures data directories for bind mounts exist.
func WriteComposeFiles(p *types.Project, imageOverride string) error {
	if err := os.MkdirAll(p.StackPath, 0755); err != nil {
		return fmt.Errorf("mkdir stack: %w", err)
	}

	// Write compose.yaml
	var composeContent string
	switch p.ConfigMode {
	case types.ConfigModeForm:
		composeContent = generateFormCompose(p)
	case types.ConfigModeCustom:
		var sc stackConfig
		if err := yaml.Unmarshal([]byte(p.CustomCompose), &sc); err != nil {
			return fmt.Errorf("parse stack config: %w", err)
		}
		if sc.ImageTag == "" {
			sc.ImageTag = "latest"
		}
		tmp := &types.Project{
			ID:            p.ID,
			RegistryImage: sc.RegistryImage,
			ImageTag:      sc.ImageTag,
			Ports:         sc.Ports,
			Volumes:       sc.Volumes,
			EnvVars:       sc.EnvVars,
			ExtraOptions:  sc.ExtraOptions,
		}
		composeContent = generateFormCompose(tmp)
		// Use env vars from stack config for .env file
		if len(sc.EnvVars) > 0 {
			p.EnvVars = sc.EnvVars
		}
		// Use volumes from stack config for directory creation
		p.Volumes = sc.Volumes
	default:
		return fmt.Errorf("unknown config_mode: %s", p.ConfigMode)
	}

	composePath := filepath.Join(p.StackPath, "compose.yaml")
	if err := os.WriteFile(composePath, []byte(composeContent), 0644); err != nil {
		return fmt.Errorf("write compose.yaml: %w", err)
	}

	// Write compose.override.yaml with pinned digest (if provided)
	overridePath := filepath.Join(p.StackPath, "compose.override.yaml")
	if imageOverride != "" {
		override := generateDigestOverride(p.ID, imageOverride)
		if err := os.WriteFile(overridePath, []byte(override), 0644); err != nil {
			return fmt.Errorf("write compose.override.yaml: %w", err)
		}
	} else {
		// Remove stale override if not applicable
		os.Remove(overridePath)
	}

	// Write .env
	if len(p.EnvVars) > 0 {
		envPath := filepath.Join(p.StackPath, ".env")
		if err := writeEnvFile(envPath, p.EnvVars); err != nil {
			return fmt.Errorf("write .env: %w", err)
		}
	}

	// Ensure bind mount host directories exist
	for _, v := range p.Volumes {
		hostPath := v.HostPath
		if !filepath.IsAbs(hostPath) {
			hostPath = filepath.Join(p.StackPath, hostPath)
		}
		if err := os.MkdirAll(hostPath, 0755); err != nil {
			return fmt.Errorf("mkdir volume %s: %w", hostPath, err)
		}
	}

	return nil
}

func generateFormCompose(p *types.Project) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by bbsit. Do not edit manually.\n")
	b.WriteString("# Changes will be overwritten on next deploy.\n\n")
	b.WriteString("services:\n")
	b.WriteString(fmt.Sprintf("  %s:\n", p.ID))
	b.WriteString(fmt.Sprintf("    image: %s:%s\n", p.RegistryImage, p.ImageTag))
	b.WriteString("    restart: unless-stopped\n")

	// Ports
	if len(p.Ports) > 0 {
		bindHost := p.BindHost
		if bindHost == "" {
			bindHost = "127.0.0.1"
		}
		b.WriteString("    ports:\n")
		for _, pm := range p.Ports {
			proto := pm.Protocol
			if proto == "" || proto == "tcp" {
				b.WriteString(fmt.Sprintf("      - \"%s:%d:%d\"\n", bindHost, pm.HostPort, pm.ContainerPort))
			} else {
				b.WriteString(fmt.Sprintf("      - \"%s:%d:%d/%s\"\n", bindHost, pm.HostPort, pm.ContainerPort, proto))
			}
		}
	}

	// Volumes
	if len(p.Volumes) > 0 {
		b.WriteString("    volumes:\n")
		for _, v := range p.Volumes {
			suffix := ""
			if v.ReadOnly {
				suffix = ":ro"
			}
			b.WriteString(fmt.Sprintf("      - \"%s:%s%s\"\n", v.HostPath, v.ContainerPath, suffix))
		}
	}

	// Env file
	if len(p.EnvVars) > 0 {
		b.WriteString("    env_file:\n")
		b.WriteString("      - .env\n")
	}

	// Extra options (raw YAML fragment, indented under the service)
	if p.ExtraOptions != "" {
		// Each line needs 4 spaces of indentation (under service)
		for _, line := range strings.Split(strings.TrimSpace(p.ExtraOptions), "\n") {
			b.WriteString("    " + line + "\n")
		}
	}

	return b.String()
}

func generateDigestOverride(serviceID, digest string) string {
	return fmt.Sprintf(`# Auto-generated by bbsit. Pins the exact image digest.
services:
  %s:
    image: %s
`, serviceID, digest)
}

func writeEnvFile(path string, vars map[string]string) error {
	var b strings.Builder
	b.WriteString("# Auto-generated by bbsit\n")
	for k, v := range vars {
		// Basic escaping: wrap value in quotes if it contains special chars
		if strings.ContainsAny(v, " \t#'\"\\$") {
			b.WriteString(fmt.Sprintf("%s=\"%s\"\n", k, strings.ReplaceAll(v, "\"", "\\\"")))
		} else {
			b.WriteString(fmt.Sprintf("%s=%s\n", k, v))
		}
	}
	return os.WriteFile(path, []byte(b.String()), 0600) // 0600: only owner can read secrets
}
