package deployer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/kingyoung/bbsit/internal/types"
	"gopkg.in/yaml.v3"
)

// stackConfig is the YAML format for stack config mode.
// It mirrors the form fields so both modes generate compose.yaml the same way.
type stackConfig struct {
	RegistryImage string              `yaml:"registry_image"`
	ImageTag      string              `yaml:"image_tag"`
	Ports         []types.PortMapping `yaml:"ports"`
	Volumes       []types.VolumeMount `yaml:"volumes"`
	EnvVars       map[string]string   `yaml:"env_vars"`
	ExtraOptions  string              `yaml:"extra_options"`
	Services      []types.ServiceConfig `yaml:"services"`
}

// WriteComposeFiles writes compose.yaml, compose.override.yaml, and .env to the stack directory.
// It also ensures data directories for bind mounts exist.
// imageOverrides maps service name -> full image reference (e.g. "registry.example.com/app@sha256:abc123").
func WriteComposeFiles(p *types.Project, imageOverrides map[string]string) error {
	if err := os.MkdirAll(p.StackPath, 0755); err != nil {
		return fmt.Errorf("mkdir stack: %w", err)
	}

	// Write compose.yaml
	var composeContent string
	switch p.ConfigMode {
	case types.ConfigModeForm:
		composeContent = generateFormCompose(p)
	case types.ConfigModeCustom:
		var sc stackConfig
		if err := yaml.Unmarshal([]byte(p.CustomCompose), &sc); err != nil {
			return fmt.Errorf("parse stack config: %w", err)
		}
		// Convert custom config to a temporary project for compose generation
		tmp := &types.Project{
			ID:       p.ID,
			BindHost: p.BindHost,
		}
		if len(sc.Services) > 0 {
			tmp.Services = sc.Services
		} else {
			if sc.ImageTag == "" {
				sc.ImageTag = "latest"
			}
			tmp.Services = []types.ServiceConfig{{
				Name:          p.ID,
				RegistryImage: sc.RegistryImage,
				ImageTag:      sc.ImageTag,
				Ports:         sc.Ports,
				Volumes:       sc.Volumes,
				ExtraOptions:  sc.ExtraOptions,
			}}
		}
		tmp.EnvVars = sc.EnvVars
		tmp.StackPath = p.StackPath
		composeContent = generateFormCompose(tmp)
		// Use env vars from stack config for .env file
		if len(sc.EnvVars) > 0 {
			p.EnvVars = sc.EnvVars
		}
	default:
		return fmt.Errorf("unknown config_mode: %s", p.ConfigMode)
	}

	composePath := filepath.Join(p.StackPath, "compose.yaml")
	if err := os.WriteFile(composePath, []byte(composeContent), 0644); err != nil {
		return fmt.Errorf("write compose.yaml: %w", err)
	}

	// Write compose.override.yaml with pinned digests (if provided)
	overridePath := filepath.Join(p.StackPath, "compose.override.yaml")
	if len(imageOverrides) > 0 {
		override := generateDigestOverride(imageOverrides)
		if err := os.WriteFile(overridePath, []byte(override), 0644); err != nil {
			return fmt.Errorf("write compose.override.yaml: %w", err)
		}
	} else {
		// Remove stale override if not applicable
		os.Remove(overridePath)
	}

	// Write .env
	if len(p.EnvVars) > 0 {
		envPath := filepath.Join(p.StackPath, ".env")
		if err := writeEnvFile(envPath, p.EnvVars); err != nil {
			return fmt.Errorf("write .env: %w", err)
		}
	}

	// Ensure bind mount host directories exist
	for _, svc := range p.Services {
		for _, v := range svc.Volumes {
			hostPath := v.HostPath
			if !filepath.IsAbs(hostPath) {
				hostPath = filepath.Join(p.StackPath, hostPath)
			}
			if err := os.MkdirAll(hostPath, 0755); err != nil {
				return fmt.Errorf("mkdir volume %s: %w", hostPath, err)
			}
		}
	}

	return nil
}

func generateFormCompose(p *types.Project) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by bbsit. Do not edit manually.\n")
	b.WriteString("# Changes will be overwritten on next deploy.\n\n")
	b.WriteString("services:\n")

	for _, svc := range p.Services {
		b.WriteString(fmt.Sprintf("  %s:\n", svc.Name))
		b.WriteString(fmt.Sprintf("    image: %s:%s\n", svc.RegistryImage, svc.ImageTag))
		b.WriteString("    restart: unless-stopped\n")

		// Ports
		if len(svc.Ports) > 0 {
			bindHost := p.BindHost
			if bindHost == "" {
				bindHost = "127.0.0.1"
			}
			b.WriteString("    ports:\n")
			for _, pm := range svc.Ports {
				proto := pm.Protocol
				if proto == "" || proto == "tcp" {
					b.WriteString(fmt.Sprintf("      - \"%s:%d:%d\"\n", bindHost, pm.HostPort, pm.ContainerPort))
				} else {
					b.WriteString(fmt.Sprintf("      - \"%s:%d:%d/%s\"\n", bindHost, pm.HostPort, pm.ContainerPort, proto))
				}
			}
		}

		// Volumes
		if len(svc.Volumes) > 0 {
			b.WriteString("    volumes:\n")
			for _, v := range svc.Volumes {
				hostPath := v.HostPath
				if !filepath.IsAbs(hostPath) {
					hostPath = filepath.Join(p.StackPath, hostPath)
				}
				suffix := ""
				if v.ReadOnly {
					suffix = ":ro"
				}
				b.WriteString(fmt.Sprintf("      - \"%s:%s%s\"\n", hostPath, v.ContainerPath, suffix))
			}
		}

		// Env file (shared across all services)
		if len(p.EnvVars) > 0 {
			b.WriteString("    env_file:\n")
			b.WriteString("      - .env\n")
		}

		// Extra options (raw YAML fragment, indented under the service)
		if svc.ExtraOptions != "" {
			for _, line := range strings.Split(strings.TrimSpace(svc.ExtraOptions), "\n") {
				b.WriteString("    " + line + "\n")
			}
		}
	}

	return b.String()
}

// generateDigestOverride creates compose.override.yaml content that pins exact image digests per service.
func generateDigestOverride(overrides map[string]string) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by bbsit. Pins the exact image digest.\n")
	b.WriteString("services:\n")
	for name, imageRef := range overrides {
		b.WriteString(fmt.Sprintf("  %s:\n", name))
		b.WriteString(fmt.Sprintf("    image: %s\n", imageRef))
	}
	return b.String()
}

func writeEnvFile(path string, vars map[string]string) error {
	var b strings.Builder
	b.WriteString("# Auto-generated by bbsit\n")
	for k, v := range vars {
		// Basic escaping: wrap value in quotes if it contains special chars
		if strings.ContainsAny(v, " \t#'\"\\$") {
			b.WriteString(fmt.Sprintf("%s=\"%s\"\n", k, strings.ReplaceAll(v, "\"", "\\\"")))
		} else {
			b.WriteString(fmt.Sprintf("%s=%s\n", k, v))
		}
	}
	return os.WriteFile(path, []byte(b.String()), 0600) // 0600: only owner can read secrets
}
